-- Seed Practice Missions (Quizzes and Essays)
-- Reset existing practice missions to allow re-running seed safely
DELETE FROM public.missions WHERE is_practice = true;

-- Insert 4 Practice Quizzes
INSERT INTO public.missions (id, title, type, topic, description, coin_reward_base, exp_reward_base, is_practice) VALUES
('f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Latihan Kuis Matematika', 'quiz', 'Matematika', 'Uji kemampuan berpikir logis dan pemecahan masalah dengan latihan soal Matematika Aljabar, Geometri, dan Kombinatorika.', 30, 30, true),
('f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Latihan Kuis Geografi', 'quiz', 'Geografi', 'Jelajahi pengetahuan tentang bentang alam, kependudukan, iklim, dan kartografi bumi.', 30, 30, true),
('f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Latihan Kuis Kimia', 'quiz', 'Kimia', 'Uji pemahamanmu tentang reaksi kimia, struktur atom, tabel periodik, dan stoikiometri.', 30, 30, true),
('f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Latihan Kuis Biologi', 'quiz', 'Biologi', 'Jelajahi keanekaragaman hayati, genetika, sel hewan & tumbuhan, serta sistem ekologi.', 30, 30, true);

-- Insert 4 Practice Essays
INSERT INTO public.missions (id, title, type, topic, description, coin_reward_base, exp_reward_base, is_practice, reference_answer) VALUES
('e1e8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Latihan Esai Matematika', 'essay', 'Matematika', 'Jelaskan peranan penting Teorema Pythagoras dalam perkembangan ilmu trigonometri modern dan berikan contoh penerapannya.', 30, 30, true, 'Teorema Pythagoras menyatakan bahwa pada segitiga siku-siku, kuadrat panjang sisi miring sama dengan jumlah kuadrat panjang kedua sisi lainnya (a^2 + b^2 = c^2). Teorema ini sangat krusial dalam trigonometri karena menjadi dasar pendefinisian fungsi trigonometri dasar seperti sinus, kosinus, dan tangen pada lingkaran satuan. Melalui teorema ini, kita dapat membuktikan identitas trigonometri utama sin^2(theta) + cos^2(theta) = 1. Contoh penerapan praktisnya meliputi navigasi udara, pemetaan tanah, arsitektur pembangunan gedung, dan perhitungan jarak langsung antara dua titik koordinat Cartesian.'),
('e1e8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Latihan Esai Geografi', 'essay', 'Geografi', 'Analisis dampak pemanasan global terhadap naiknya permukaan air laut di wilayah pesisir Indonesia dan upaya mitigasinya.', 30, 30, true, 'Pemanasan global memicu kenaikan suhu bumi yang menyebabkan mencairnya es di kutub serta ekspansi termal air laut, sehingga volume air laut meningkat. Dampaknya bagi wilayah pesisir Indonesia sangat signifikan karena Indonesia merupakan negara kepulauan. Dampak tersebut meliputi abrasi pantai yang parah, tenggelamnya pulau-pulau kecil, intrusi air laut ke sumber air tanah tawar, serta banjir rob tahunan di kota-kota pesisir seperti Jakarta Utara dan Semarang. Upaya mitigasi yang relevan mencakup penanaman hutan bakau (mangrove) untuk menahan ombak, pembangunan tanggul laut raksasa, relokasi permukiman rentan, serta transisi ke energi terbarukan untuk menekan laju emisi karbon global.'),
('e1e8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Latihan Esai Kimia', 'essay', 'Kimia', 'Jelaskan perbedaan mendasar antara ikatan kovalen polar dan kovalen nonpolar serta berikan contoh senyawa nyatanya.', 30, 30, true, 'Perbedaan mendasar antara ikatan kovalen polar dan nonpolar terletak pada distribusi elektron dan perbedaan elektronegativitas antara atom-atom yang berikatan. Pada ikatan kovalen polar, terjadi pembagian elektron yang tidak merata karena salah satu atom memiliki elektronegativitas yang jauh lebih tinggi sehingga menarik pasangan elektron lebih kuat (membentuk kutub atau dipol). Contoh senyawa polar adalah Air (H2O) dan Asam Klorida (HCl). Sebaliknya, pada ikatan kovalen nonpolar, pasangan elektron terbagi secara merata di antara atom-atom yang berikatan karena memiliki elektronegativitas yang sama atau hampir sama. Contoh senyawa nonpolar adalah gas Oksigen (O2), gas Nitrogen (N2), dan Metana (CH4).'),
('e1e8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Latihan Esai Biologi', 'essay', 'Biologi', 'Jelaskan proses fotosintesis pada tumbuhan hijau, perbedaan reaksi terang dan gelap, serta faktor yang mempengaruhinya.', 30, 30, true, 'Fotosintesis adalah proses biokimia yang dilakukan tumbuhan hijau untuk memproduksi karbohidrat dari karbon dioksida dan air dengan bantuan energi cahaya matahari dan klorofil. Fotosintesis terdiri dari dua tahapan: Reaksi Terang dan Reaksi Gelap (Siklus Calvin). Reaksi terang berlangsung di grana kloroplas dan mutlak membutuhkan cahaya matahari untuk memecah air (fotolisis) menjadi oksigen serta menghasilkan ATP dan NADPH. Reaksi gelap berlangsung di stroma kloroplas tanpa membutuhkan cahaya secara langsung, menggunakan ATP dan NADPH hasil reaksi terang untuk mereduksi karbon dioksida menjadi glukosa. Faktor-faktor utama yang mempengaruhinya meliputi intensitas cahaya matahari, konsentrasi karbon dioksida di udara, suhu lingkungan, ketersediaan air, dan kandungan klorofil tumbuhan.');

-- Insert Questions for Latihan Kuis Matematika
INSERT INTO public.quiz_questions (id, mission_id, question, options, correct_answer, explanation, order_index) VALUES
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Jika nilai 2x + 5 = 15, berapakah nilai x?', '[{"label": "A", "text": "5"}, {"label": "B", "text": "10"}, {"label": "C", "text": "15"}, {"label": "D", "text": "20"}]'::jsonb, 'A', 'Kurangi kedua ruas dengan 5: 2x = 10. Bagi kedua ruas dengan 2: x = 5.', 1),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Berapakah hasil perhitungan dari 5 * 6 - 8?', '[{"label": "A", "text": "20"}, {"label": "B", "text": "22"}, {"label": "C", "text": "24"}, {"label": "D", "text": "26"}]'::jsonb, 'B', 'Kerjakan perkalian terlebih dahulu: 5 * 6 = 30. Lalu lakukan pengurangan: 30 - 8 = 22.', 2),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Berapakah besar sudut dalam pada setiap sudut segitiga sama sisi?', '[{"label": "A", "text": "45 derajat"}, {"label": "B", "text": "60 derajat"}, {"label": "C", "text": "90 derajat"}, {"label": "D", "text": "120 derajat"}]'::jsonb, 'B', 'Total sudut dalam segitiga adalah 180 derajat. Karena segitiga sama sisi ketiga sudutnya sama besar, maka 180 / 3 = 60 derajat.', 3),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Berapakah akar kuadrat positif dari 144?', '[{"label": "A", "text": "11"}, {"label": "B", "text": "12"}, {"label": "C", "text": "13"}, {"label": "D", "text": "14"}]'::jsonb, 'B', 'Akar kuadrat dari 144 adalah 12, karena 12 * 12 = 144.', 4),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Tentukan suku ke-5 dari barisan aritmatika berikut: 3, 7, 11, 15...', '[{"label": "A", "text": "17"}, {"label": "B", "text": "18"}, {"label": "C", "text": "19"}, {"label": "D", "text": "20"}]'::jsonb, 'C', 'Beda barisan (b) adalah 4. Suku ke-5 (U5) = U4 + b = 15 + 4 = 19.', 5),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Jika x^2 - 4 = 0, berapakah nilai x yang memenuhi?', '[{"label": "A", "text": "2 atau -2"}, {"label": "B", "text": "4 atau -4"}, {"label": "C", "text": "0"}, {"label": "D", "text": "1"}]'::jsonb, 'A', 'x^2 = 4, maka x = akar(4) yang menghasilkan 2 atau -2.', 6),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Berapakah luas lingkaran dengan jari-jari 7 cm? (Gunakan pi = 22/7)', '[{"label": "A", "text": "150 cm^2"}, {"label": "B", "text": "154 cm^2"}, {"label": "C", "text": "160 cm^2"}, {"label": "D", "text": "164 cm^2"}]'::jsonb, 'B', 'Luas = pi * r^2 = 22/7 * 7 * 7 = 154 cm^2.', 7),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Tentukan modus dari sekumpulan data berikut: 2, 3, 3, 4, 5, 5, 5, 6', '[{"label": "A", "text": "3"}, {"label": "B", "text": "4"}, {"label": "C", "text": "5"}, {"label": "D", "text": "6"}]'::jsonb, 'C', 'Modus adalah nilai yang paling sering muncul. Angka 5 muncul sebanyak 3 kali (paling banyak).', 8),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Berapakah gradien (kemiringan) dari persamaan garis y = 3x - 5?', '[{"label": "A", "text": "3"}, {"label": "B", "text": "-3"}, {"label": "C", "text": "5"}, {"label": "D", "text": "-5"}]'::jsonb, 'A', 'Persamaan berbentuk y = mx + c, di mana m menyatakan gradien. Jadi gradiennya adalah 3.', 9),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b01', 'Berapakah peluang munculnya angka genap pada pelemparan satu buah dadu bersisi enam?', '[{"label": "A", "text": "1/2"}, {"label": "B", "text": "1/3"}, {"label": "C", "text": "1/4"}, {"label": "D", "text": "1/6"}]'::jsonb, 'A', 'Angka genap pada dadu adalah 2, 4, 6 (3 angka). Total sisi dadu adalah 6. Peluang = 3/6 = 1/2.', 10);

-- Insert Questions for Latihan Kuis Geografi
INSERT INTO public.quiz_questions (id, mission_id, question, options, correct_answer, explanation, order_index) VALUES
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Apakah nama ibu kota dari negara Australia?', '[{"label": "A", "text": "Sydney"}, {"label": "B", "text": "Melbourne"}, {"label": "C", "text": "Canberra"}, {"label": "D", "text": "Brisbane"}]'::jsonb, 'C', 'Ibu kota federasi Australia adalah Canberra, dirancang khusus sebagai ibu kota menggantikan persaingan Sydney dan Melbourne.', 1),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Apakah benua dengan luas wilayah terkecil di dunia?', '[{"label": "A", "text": "Asia"}, {"label": "B", "text": "Australia"}, {"label": "C", "text": "Eropa"}, {"label": "D", "text": "Afrika"}]'::jsonb, 'B', 'Benua Australia/Oseania adalah benua terkecil di bumi baik berdasarkan populasi maupun luas wilayah daratan.', 2),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Garis khayal yang membagi bumi menjadi belahan bumi utara dan selatan disebut...', '[{"label": "A", "text": "Khatulistiwa"}, {"label": "B", "text": "Greenwich"}, {"label": "C", "text": "Bujur"}, {"label": "D", "text": "Lintang"}]'::jsonb, 'A', 'Garis khatulistiwa atau ekuator membagi bumi secara horizontal menjadi belahan utara dan selatan.', 3),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Apakah nama gurun pasir terluas di dunia?', '[{"label": "A", "text": "Gurun Gobi"}, {"label": "B", "text": "Gurun Sahara"}, {"label": "C", "text": "Gurun Kalahari"}, {"label": "D", "text": "Gurun Mojave"}]'::jsonb, 'B', 'Gurun Sahara di Afrika Utara adalah gurun pasir panas terbesar dan terluas di dunia.', 4),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Samudra apakah yang terkenal sebagai samudra terdalam di dunia?', '[{"label": "A", "text": "Samudra Hindia"}, {"label": "B", "text": "Samudra Atlantik"}, {"label": "C", "text": "Samudra Pasifik"}, {"label": "D", "text": "Samudra Arktik"}]'::jsonb, 'C', 'Samudra Pasifik memiliki kedalaman rata-rata terbesar dan menampung Palung Mariana (titik terdalam bumi).', 5),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Apakah nama danau vulkanik terbesar di Indonesia?', '[{"label": "A", "text": "Danau Toba"}, {"label": "B", "text": "Danau Singkarak"}, {"label": "C", "text": "Danau Poso"}, {"label": "D", "text": "Danau Sentani"}]'::jsonb, 'A', 'Danau Toba di Sumatra Utara merupakan danau vulkanik terbesar di Indonesia dan Asia Tenggara.', 6),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Apakah nama gunung tertinggi di dunia di atas permukaan laut?', '[{"label": "A", "text": "Gunung Kilimanjaro"}, {"label": "B", "text": "Gunung Everest"}, {"label": "C", "text": "Gunung Fuji"}, {"label": "D", "text": "Gunung Jaya Wijaya"}]'::jsonb, 'B', 'Gunung Everest yang terletak di pegunungan Himalaya merupakan gunung tertinggi di dunia (8.848 meter).', 7),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Jenis batuan yang terbentuk langsung dari pembekuan dan pendinginan magma disebut...', '[{"label": "A", "text": "Batuan Sedimen"}, {"label": "B", "text": "Batuan Beku"}, {"label": "C", "text": "Batuan Metamorf"}, {"label": "D", "text": "Batuan Kapur"}]'::jsonb, 'B', 'Batuan beku terbentuk dari pembekuan cairan magma baik di bawah permukaan bumi (intrusif) maupun di atas permukaan bumi (ekstrusif).', 8),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Selat yang memisahkan pulau Jawa dan pulau Sumatra adalah...', '[{"label": "A", "text": "Selat Karimata"}, {"label": "B", "text": "Selat Sunda"}, {"label": "C", "text": "Selat Bali"}, {"label": "D", "text": "Selat Malaka"}]'::jsonb, 'B', 'Selat Sunda menghubungkan pulau Jawa dan Sumatra, serta menjadi lokasi Gunung Anak Krakatau.', 9),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b02', 'Negara manakah yang terkenal sebagai salah satu lumbung padi utama di Asia Tenggara?', '[{"label": "A", "text": "Indonesia"}, {"label": "B", "text": "Thailand"}, {"label": "C", "text": "Vietnam"}, {"label": "D", "text": "Filipina"}]'::jsonb, 'B', 'Thailand secara historis dikenal sebagai eksportir beras terbesar dan berjuluk lumbung padi Asia Tenggara.', 10);

-- Insert Questions for Latihan Kuis Kimia
INSERT INTO public.quiz_questions (id, mission_id, question, options, correct_answer, explanation, order_index) VALUES
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Apakah lambang unsur kimia untuk logam Emas?', '[{"label": "A", "text": "Au"}, {"label": "B", "text": "Ag"}, {"label": "C", "text": "Fe"}, {"label": "D", "text": "Cu"}]'::jsonb, 'A', 'Lambang unsur emas adalah Au, berasal dari bahasa Latin "Aurum" yang berarti fajar yang berkilau.', 1),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Apakah rumus kimia yang menyatakan senyawa Air?', '[{"label": "A", "text": "CO2"}, {"label": "B", "text": "H2O"}, {"label": "C", "text": "NaCl"}, {"label": "D", "text": "CH4"}]'::jsonb, 'B', 'Air terdiri dari dua atom hidrogen dan satu atom oksigen, dirumuskan sebagai H2O.', 2),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Partikel subatomik penyusun inti atom yang bermuatan negatif adalah...', '[{"label": "A", "text": "Proton"}, {"label": "B", "text": "Neutron"}, {"label": "C", "text": "Elektron"}, {"label": "D", "text": "Positron"}]'::jsonb, 'C', 'Elektron bermuatan negatif (-1) dan mengitari inti atom pada kulit-kulit atom.', 3),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Berapakah nilai pH untuk larutan netral pada suhu standar 25 derajat Celsius?', '[{"label": "A", "text": "0"}, {"label": "B", "text": "5"}, {"label": "C", "text": "7"}, {"label": "D", "text": "14"}]'::jsonb, 'C', 'Larutan netral (seperti air murni) memiliki kadar pH tepat sebesar 7.', 4),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Gas manakah yang menjadi penyebab utama efek rumah kaca di atmosfer bumi?', '[{"label": "A", "text": "Oksigen"}, {"label": "B", "text": "Nitrogen"}, {"label": "C", "text": "Karbon Dioksida"}, {"label": "D", "text": "Helium"}]'::jsonb, 'C', 'Gas CO2 (Karbon Dioksida) yang dihasilkan dari pembakaran bahan bakar fosil adalah kontributor utama pemanasan global.', 5),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Asam utama yang menyusun cairan lambung manusia adalah...', '[{"label": "A", "text": "Asam Sulfat"}, {"label": "B", "text": "Asam Klorida"}, {"label": "C", "text": "Asam Asetat"}, {"label": "D", "text": "Asam Nitrat"}]'::jsonb, 'B', 'Lambung mensekresi Asam Klorida (HCl) yang sangat asam untuk mencerna makanan dan membunuh bakteri.', 6),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Zat yang berfungsi mempercepat laju reaksi tanpa ikut habis bereaksi disebut...', '[{"label": "A", "text": "Inhibitor"}, {"label": "B", "text": "Katalis"}, {"label": "C", "text": "Reaktan"}, {"label": "D", "text": "Produk"}]'::jsonb, 'B', 'Katalis mempercepat reaksi dengan menurunkan energi aktivasi reaksi tanpa dikonsumsi secara permanen.', 7),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Apakah nama unsur dengan nomor atom 1 pada tabel periodik?', '[{"label": "A", "text": "Helium"}, {"label": "B", "text": "Hidrogen"}, {"label": "C", "text": "Litium"}, {"label": "D", "text": "Karbon"}]'::jsonb, 'B', 'Hidrogen (H) memiliki nomor atom 1 karena hanya memiliki 1 proton di dalam intinya.', 8),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Apakah rumus kimia dari garam dapur?', '[{"label": "A", "text": "NaOH"}, {"label": "B", "text": "HCl"}, {"label": "C", "text": "NaCl"}, {"label": "D", "text": "CaCO3"}]'::jsonb, 'C', 'Garam dapur adalah Natrium Klorida, yang dirumuskan secara kimia sebagai NaCl.', 9),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b03', 'Reaksi kimia yang melepaskan energi panas/kalor ke lingkungan sekitar disebut...', '[{"label": "A", "text": "Reaksi Endoterm"}, {"label": "B", "text": "Reaksi Eksoterm"}, {"label": "C", "text": "Reaksi Oksidasi"}, {"label": "D", "text": "Reaksi Reduksi"}]'::jsonb, 'B', 'Reaksi eksoterm melepaskan energi panas sehingga menaikkan suhu wadah/lingkungan sekitarnya.', 10);

-- Insert Questions for Latihan Kuis Biologi
INSERT INTO public.quiz_questions (id, mission_id, question, options, correct_answer, explanation, order_index) VALUES
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Apakah satuan unit struktural dan fungsional terkecil dari makhluk hidup?', '[{"label": "A", "text": "Jaringan"}, {"label": "B", "text": "Organ"}, {"label": "C", "text": "Sel"}, {"label": "D", "text": "Sistem Organ"}]'::jsonb, 'C', 'Sel adalah unit terkecil dari kehidupan yang menyusun semua makhluk hidup.', 1),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Bagian tumbuhan yang berfungsi menyerap air dan hara mineral dari dalam tanah adalah...', '[{"label": "A", "text": "Daun"}, {"label": "B", "text": "Batang"}, {"label": "C", "text": "Akar"}, {"label": "D", "text": "Bunga"}]'::jsonb, 'C', 'Akar memiliki rambut-rambut akar yang berfungsi memperluas penyerapan air dan hara dari tanah.', 2),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Proses pembentukan zat makanan oleh tumbuhan hijau berbantuan cahaya disebut...', '[{"label": "A", "text": "Respirasi"}, {"label": "B", "text": "Fotosintesis"}, {"label": "C", "text": "Transpirasi"}, {"label": "D", "text": "Asimilasi"}]'::jsonb, 'B', 'Fotosintesis mengubah CO2 dan H2O menjadi zat gula/glukosa dan O2 berbantuan cahaya matahari dan klorofil.', 3),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Pembuluh darah yang mengalirkan darah keluar dari jantung menuju seluruh tubuh disebut...', '[{"label": "A", "text": "Pembuluh Arteri"}, {"label": "B", "text": "Pembuluh Vena"}, {"label": "C", "text": "Pembuluh Kapiler"}, {"label": "D", "text": "Aorta"}]'::jsonb, 'A', 'Arteri (nadi) membawa darah kaya oksigen keluar dari jantung (kecuali arteri pulmonalis).', 4),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Apakah organ utama alat pernapasan pada hewan golongan Ikan?', '[{"label": "A", "text": "Paru-paru"}, {"label": "B", "text": "Trakea"}, {"label": "C", "text": "Insang"}, {"label": "D", "text": "Kulit"}]'::jsonb, 'C', 'Ikan bernapas menggunakan insang yang mengekstrak oksigen terlarut dari air.', 5),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Penyakit malaria ditularkan melalui nyamuk akibat infeksi parasit...', '[{"label": "A", "text": "Amoeba"}, {"label": "B", "text": "Plasmodium"}, {"label": "C", "text": "Virus Dengue"}, {"label": "D", "text": "Bakteri"}]'::jsonb, 'B', 'Malaria disebabkan oleh protozoa parasit bersel tunggal dari genus Plasmodium.', 6),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Organ tubuh manusia manakah yang berfungsi utama menetralkan racun (detoksifikasi)?', '[{"label": "A", "text": "Ginjal"}, {"label": "B", "text": "Hati"}, {"label": "C", "text": "Jantung"}, {"label": "D", "text": "Paru-paru"}]'::jsonb, 'B', 'Hati (lever) mendegradasi zat kimia beracun dan obat-obatan yang masuk ke tubuh agar aman dibuang.', 7),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Bagian sel tumbuhan manakah yang berfungsi memberikan bentuk kaku dan tidak dimiliki sel hewan?', '[{"label": "A", "text": "Dinding Sel"}, {"label": "B", "text": "Membran Sel"}, {"label": "C", "text": "Sitoplasma"}, {"label": "D", "text": "Inti Sel"}]'::jsonb, 'A', 'Dinding sel yang terbuat dari selulosa hanya dimiliki oleh tumbuhan dan berfungsi memperkokoh struktur sel.', 8),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Hubungan timbal balik antara makhluk hidup dengan komponen abiotik lingkungannya membentuk...', '[{"label": "A", "text": "Ekosistem"}, {"label": "B", "text": "Ekologi"}, {"label": "C", "text": "Habitat"}, {"label": "D", "text": "Populasi"}]'::jsonb, 'A', 'Ekosistem adalah kesatuan fungsional antara komunitas biotik (makhluk hidup) dan faktor abiotik lingkungannya.', 9),
(gen_random_uuid(), 'f1f8fa16-67a6-4c40-b88a-35a0d60d0b04', 'Apakah kepanjangan yang benar dari DNA?', '[{"label": "A", "text": "Deoxyribonucleic Acid"}, {"label": "B", "text": "Ribonucleic Acid"}, {"label": "C", "text": "Dioxyribo Acid"}, {"label": "D", "text": "Detoxy Acid"}]'::jsonb, 'A', 'DNA singkatan dari Deoxyribonucleic Acid (Asam Deoksiribonukleat), pembawa materi genetika makhluk hidup.', 10);
