export const mockCards = [
  {
    id: "card-legendary-1",
    name: "Profesor Fisika",
    rarity: "Legendary",
    subject: "Fisika",
    quote: "Semesta diatur oleh hukum-hukum elegan yang menanti dipecahkan.",
    description: "Sang penguasa mekanika dan relativitas. Selalu melihat pola matematika di balik hembusan angin maupun guguran bintang.",
    image_url: "/cards/physics_professor.jpg",
    stats: { Logika: 98, Kreativitas: 88, Penulisan: 85, Riset: 95 },
    icon: "auto_awesome",
    bgClass: "from-[#d4af37] via-[#fff3cd] to-[#aa7c11]",
    textClass: "text-[#856404]",
    borderClass: "border-[#d4af37]",
    glowClass: "shadow-[0_0_20px_rgba(212,175,55,0.4)]",
    passiveBoost: "+20% Koin/XP untuk Fisika & Sains, +5% untuk semua aktivitas (Maksimal +25%)",
    passiveBoostShort: "+25% Fisika & Sains"
  },
  {
    id: "card-legendary-2",
    name: "Filsuf Kebijaksanaan",
    rarity: "Legendary",
    subject: "Filsafat",
    quote: "Berpikir kritis adalah awal dari pembebasan pikiran.",
    description: "Penjaga tradisi dialektika kuno yang menguji segala dogma. Menolong muridnya menemukan kebenaran sejati lewat pertanyaan kritis.",
    image_url: "/cards/philosopher.jpg",
    stats: { Logika: 99, Kreativitas: 92, Penulisan: 94, Riset: 89 },
    icon: "psychology",
    bgClass: "from-[#d4af37] via-[#fdf9ee] to-[#aa7c11]",
    textClass: "text-[#856404]",
    borderClass: "border-[#d4af37]",
    glowClass: "shadow-[0_0_20px_rgba(212,175,55,0.4)]",
    passiveBoost: "+15% Koin/XP untuk Semua Subjek, +5% jika mengerjakan misi Esai (Maksimal +20%)",
    passiveBoostShort: "+20% Esai (Global)"
  },
  {
    id: "card-epic-1",
    name: "Penyihir Matematika",
    rarity: "Epic",
    subject: "Matematika",
    quote: "Mengendalikan dunia dengan rumus dan persamaan kuadrat.",
    description: "Mampu melipat waktu dan menghitung bintang dalam sekejap dengan kombinatorika dan deret tak hingga.",
    image_url: "/cards/math_wizard.jpg",
    stats: { Logika: 94, Kreativitas: 82, Penulisan: 70, Riset: 88 },
    icon: "functions",
    bgClass: "from-[#8e44ad] via-[#f5eef8] to-[#6c3483]",
    textClass: "text-[#6c3483]",
    borderClass: "border-[#8e44ad]",
    glowClass: "shadow-[0_0_15px_rgba(142,68,173,0.3)]",
    passiveBoost: "+15% Koin/XP untuk Matematika, +5% jika mengerjakan misi Kuis (Maksimal +20%)",
    passiveBoostShort: "+20% Kuis (Matematika)"
  },
  {
    id: "card-epic-2",
    name: "Sastrawan Pujangga",
    rarity: "Epic",
    subject: "Sastra",
    quote: "Kata-kata memiliki kekuatan untuk menggerakkan jiwa.",
    description: "Pujangga klasik yang merangkai metafora kematian and cinta menjadi bait-bait yang melintasi zaman sastra Indonesia modern.",
    image_url: "/cards/poet.jpg",
    stats: { Logika: 75, Kreativitas: 96, Penulisan: 98, Riset: 80 },
    icon: "history_edu",
    bgClass: "from-[#8e44ad] via-[#fbf7fc] to-[#6c3483]",
    textClass: "text-[#6c3483]",
    borderClass: "border-[#8e44ad]",
    glowClass: "shadow-[0_0_15px_rgba(142,68,173,0.3)]",
    passiveBoost: "+15% Koin/XP untuk Sastra, +5% jika mengerjakan misi Esai (Maksimal +20%)",
    passiveBoostShort: "+20% Esai (Sastra)"
  },
  {
    id: "card-rare-1",
    name: "Ksatria Sejarah",
    rarity: "Rare",
    subject: "Sejarah",
    quote: "Membela kebenaran berdasarkan data dan arsip otentik.",
    description: "Mengelilingi dunia demi mencari gulungan manuskrip kuno untuk menyusun kebenaran linimasa peradaban.",
    image_url: "/cards/history_knight.jpg",
    stats: { Logika: 85, Kreativitas: 78, Penulisan: 86, Riset: 90 },
    icon: "museum",
    bgClass: "from-[#2980b9] via-[#ebf5fb] to-[#1f618d]",
    textClass: "text-[#1f618d]",
    borderClass: "border-[#2980b9]",
    glowClass: "shadow-[0_0_10px_rgba(41,128,185,0.2)]",
    passiveBoost: "+10% Koin/XP untuk Sejarah, +5% untuk semua tipe aktivitas (Maksimal +15%)",
    passiveBoostShort: "+15% Sejarah"
  },
  {
    id: "card-rare-2",
    name: "Astronom Muda",
    rarity: "Rare",
    subject: "Sains",
    quote: "Bintang-bintang adalah peta petualangan masa depan.",
    description: "Menatap langit malam lewat teleskop buatan sendiri, melukis konstelasi zodiak, dan memprediksi badai matahari.",
    image_url: "/cards/astronomer.jpg",
    stats: { Logika: 88, Kreativitas: 84, Penulisan: 76, Riset: 85 },
    icon: "telescope",
    bgClass: "from-[#2980b9] via-[#ebf5fb] to-[#1f618d]",
    textClass: "text-[#1f618d]",
    borderClass: "border-[#2980b9]",
    glowClass: "shadow-[0_0_10px_rgba(41,128,185,0.2)]",
    passiveBoost: "+10% Koin/XP untuk Sains & Fisika, +5% untuk semua tipe aktivitas (Maksimal +15%)",
    passiveBoostShort: "+15% Sains & Fisika"
  },
  {
    id: "card-common-1",
    name: "Asisten Lab Kimia",
    rarity: "Common",
    subject: "Sains",
    quote: "Reaksi terkendali menghasilkan penemuan terbaik.",
    description: "Selalu sibuk membersihkan tabung reaksi dan mencatat perubahan suhu cairan asam-basa.",
    image_url: "/cards/chemistry_assistant.png",
    stats: { Logika: 78, Kreativitas: 70, Penulisan: 68, Riset: 75 },
    icon: "science",
    bgClass: "from-[#7f8c8d] via-[#f2f4f4] to-[#5d6d7e]",
    textClass: "text-[#5d6d7e]",
    borderClass: "border-[#7f8c8d]",
    glowClass: "shadow-none",
    passiveBoost: "+5% Koin/XP untuk Kimia & Sains, +5% untuk semua tipe aktivitas (Maksimal +10%)",
    passiveBoostShort: "+10% Kimia & Sains"
  },
  {
    id: "card-common-2",
    name: "Magang Sejarah",
    rarity: "Common",
    subject: "Sejarah",
    quote: "Belajar dari masa lalu untuk memahami masa depan.",
    description: "Menyalin arsip tua dan membersihkan arca kuno di bawah pengawasan kurator museum nasional.",
    image_url: "/cards/history_apprentice.png",
    stats: { Logika: 70, Kreativitas: 72, Penulisan: 78, Riset: 72 },
    icon: "book",
    bgClass: "from-[#7f8c8d] via-[#f2f4f4] to-[#5d6d7e]",
    textClass: "text-[#5d6d7e]",
    borderClass: "border-[#7f8c8d]",
    glowClass: "shadow-none",
    passiveBoost: "+5% Koin/XP untuk Sejarah, +5% untuk semua tipe aktivitas (Maksimal +10%)",
    passiveBoostShort: "+10% Sejarah"
  }
];
